dist: xenial
language: c
env:
  matrix:
    - BUILD_NAME="default"
    - BUILD_NAME="utmp" FORCE_UTMP="1"
    - BUILD_NAME="default+tls" QMAIL_PATCH=""
    - BUILD_NAME="TLS" QMAIL_PATCH="http://inoa.net/qmail-tls/netqmail-1.06-tls-20190517.patch"
compiler:
 - gcc
 - clang
script:
 - echo "${CC} -O2 -Wall" > conf-cc
 - if [ -n "${FORCE_UTMP}" ]; then export MAKEFLAGS="${MAKEFLAGS} -o qtmp.h"; cp qtmp.h1 qtmp.h; fi
 - if [ -n "${QMAIL_PATCH}" ]; then wget -O extra.patch "${QMAIL_PATCH}" && patch -p1 -i extra.patch; fi
 - sed "s/^cc /${CC} -Wall /" -i conf-cc
 - make ${MAKEFLAGS} it man
 - env DESTDIR=/tmp/qmail make ${MAKEFLAGS} package
 - sudo make ${MAKEFLAGS} package
 - sudo groupadd -g 200 nofiles
 - sudo groupadd -g 201 qmail
 - sudo useradd -u 200 -g 200 -d /var/qmail/alias alias
 - sudo useradd -u 201 -g 200 -d /var/qmail qmaild
 - sudo useradd -u 202 -g 200 -d /var/qmail qmaill
 - sudo useradd -u 203 -g 200 -d /var/qmail qmailp
 - sudo useradd -u 204 -g 201 -d /var/qmail qmailq
 - sudo useradd -u 205 -g 201 -d /var/qmail qmailr
 - sudo useradd -u 206 -g 201 -d /var/qmail qmails
 - sudo ./instchown
 - sudo make ${MAKEFLAGS} check
 - sudo rm -rf /var/qmail
 - sudo make ${MAKEFLAGS} setup check
